version: "2"
services:
  database:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dol
    build:
      context: .
      dockerfile: Dockerfile.database
    expose:
      - "3306"
    ports:
      - 3306:3306
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - database
    stdin_open: true
    tty: true
    ports:
      - "10000-11000:10000-11000"
